baseURL = 'https://diegomellizo.com/'
DefaultContentLanguage = "en"
languageCode = 'en-us'
title = 'Diego Mellizo | Game Developer'
theme = 'lightbi-hugo'
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
googleAnalytics = "UA-237419416-1"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 99  # 99 turns off pagination.
summaryLength  = "30"

[Params]
selfHosted = true
mainSections = []
dateFormat = "2 January 2023"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = false
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = false
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = true
authorInfo = "She was born to be free, let her run wild in her own way and you will never lose her."
description = "Your can add your website description here."
previewCardImagePlacement = "top"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Author]
  name = "Diego Mellizo"
  website = "https://diegomellizo.com/"
  email = "diegomellizo@outlook.com"
  #facebook = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #twitter = "username"
  #threads = "username"
  linkedin = "diego-alexander-mellizo-cañón-0a199985"
  #github = "username"
  #gitlab = "username"
  #bitbucket = "username"
  #reddit = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[languages]
[languages.en]
contentDir = "content/en"
languageName = "English"
languageNameShort = "en"
weight = 1
[languages.es]
contentDir = "content/es"
languageName = "Spanish"
languageNameShort = "es"
weight = 2
# Menus - English.
[[languages.en.menus.main]]
    name = "Home"
    url = "/"
    weight = 1
[[languages.en.menus.main]]
    name = "Professional projects"
    url = "/professional-projects/"
    weight = 2
[[languages.en.menus.main]]
    name = "Personal projects"
    url = "/personal-projects/"
    weight = 3
[[languages.en.menus.main]]
    name = "Contact me"
    url = "/contact-me/"
    weight = 4
# Menus - Spanish.
[[languages.es.menus.main]]
name = "Inicio"
url = "/"
weight = 1
[[languages.es.menus.main]]
name = "Proyectos profesionales"
url = "/professional-projects/"
weight = 2
[[languages.es.menus.main]]
name = "Proyectos personales"
url = "/personal-projects/"
weight = 3
[[languages.es.menus.main]]
name = "Contáctame"
url = "/contact-me/"
weight = 4

[module]
[[module.imports]]
path = 'github.com/hugomods/icons/vendors/mdi'
[[module.imports]]
path = 'github.com/hugomods/video-js'
